In [1]:
#if dont have cuda enabled gpu then download pytorch cpu as light weight

In [2]:
import torch
print(torch.__version__)

2.4.1


In [3]:
device= torch.device('mps')

In [4]:
my_tensor= torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], 
                        dtype= torch.float32,
                        device= device, #if have cuda then tensor should be on gpu
                        requires_grad= True, #requires for auto grad, when we want gradient to be computed in backpropogation in computation graph
                        ) 
my_tensor

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], device='mps:0', requires_grad=True)

In [5]:
my_tensor.device, my_tensor.dtype, my_tensor.shape, my_tensor.requires_grad

(device(type='mps', index=0), torch.float32, torch.Size([2, 4]), True)

In [6]:
x= torch.empty((3, 3), dtype= torch.float16) #can be any random value
x= torch.zeros((3, 3))
x= torch.rand((3, 3))
x= torch.ones((3, 3))
x= torch.eye(3, 5)
x= torch.arange(start= 0, end= 6, step= 1)
x= torch.linspace(start= 0, end= 1, steps= 10)
x= torch.empty((5, 5)).normal_(mean= 0, std= 1) #convert values to normal dist
x= torch.empty((5, 5)).uniform_(1, 1)
x= torch.diag(torch.ones(3, 3))
x

tensor([1., 1., 1.])

In [7]:
#type conversion
x= torch.arange(4)
print(x.bool())
print(x.short()) #int16
print(x.long()) #int64
print(x.half()) #float16, in newer gpus cann train model on float16, benefitial
print(x.float()) #float32
print(x.double()) #float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [8]:
import numpy as np
x= np.ones((1, 5))
print(x)
y= torch.from_numpy(x)
print(y)
print(y.numpy()) #there can be some roundoff errors in converting and reversing

[[1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1. 1. 1.]]


In [9]:
x= torch.tensor([1, 2, 3])
y= torch.tensor([0, 8, 7])

In [10]:
#addition
z= torch.empty(3)
torch.add(x, y, out= z)

z= torch.add(x, y)

z= x+y

In [11]:
#subtraction
x-y

tensor([ 1, -6, -4])

In [12]:
#division
#do element wise divisio if same size
torch.true_divide(x, y)[0]

tensor(inf)

In [13]:
#if want to do inplace operation, storing result in the input value
t= torch.zeros(3)
t.add_(x) #if have _ then that means inplace op
print(t)
t+=x  #t=t+x is not inplace as it cpies values first
print(t)

tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [14]:
#exponentiation
z= x.pow(2)
z= x**2
print(z)

tensor([1, 4, 9])


In [15]:
#comparision
x>0
x<0

tensor([False, False, False])

In [16]:
#matrix multiplication
x1= torch.rand((2, 5))
x2= torch.rand((5, 3))
torch.mm(x1, x2) 
x1.mm(x2)

tensor([[1.3542, 1.5181, 1.8542],
        [1.0709, 1.3639, 1.3832]])

In [17]:
#matrix exponentiation
mat= torch.rand((5, 5))
mat.matrix_power(3)

tensor([[4.5613, 5.2852, 3.6514, 4.7757, 3.0372],
        [2.4616, 2.9234, 1.9319, 2.6519, 1.7105],
        [1.1889, 1.2928, 0.8354, 1.1576, 0.7699],
        [3.7526, 4.4170, 2.7928, 3.7984, 2.5673],
        [3.3753, 4.0835, 2.5942, 3.6152, 2.2780]])

In [18]:
#element wise multiplication
x*y

tensor([ 0, 16, 21])

In [19]:
#dot product

torch.dot(x, y)

tensor(37)

In [20]:
# batch matrix multiplicaiton
batch= 128
n= 10
m= 20
p= 30

#z= torch.bmm(torch.rand((batch, n, m)), torch.rand((batch, m, p)))
z= torch.bmm(torch.rand((batch, n, m), device= device), torch.rand((batch, m, p), device= device)) #this is very very fast,so batching is must to be enables
z.shape

torch.Size([128, 10, 30])

In [22]:
#example of broadcasting

x1= torch.rand((5, 5))
x2= torch.rand((1, 5))

x1- x2 #broadcasting, x2 is copied 5 times row-wise to match x1
x1** x2

tensor([[0.4961, 0.8222, 0.7686, 0.9896, 0.6527],
        [0.6132, 0.4360, 0.3214, 0.9994, 0.4876],
        [0.9571, 0.7713, 0.4810, 0.9916, 0.9056],
        [0.5745, 0.4063, 0.7389, 0.9838, 0.4540],
        [0.4207, 0.7340, 0.6385, 0.9970, 0.6750]])

In [29]:
tensor1= torch.rand((batch, n, m))
torch.sum(tensor1, dim= 2).shape

torch.Size([128, 10])

In [36]:
val, ind= tensor1.max(dim= 2)
val, ind= tensor1.min(dim= 2)
val.shape, ind.shape

(torch.Size([128, 10]), torch.Size([128, 10]))

In [38]:
torch.abs(x)

tensor([1, 2, 3])

In [41]:
torch.argmax(tensor1, dim= 0).shape
torch.argmin(tensor1, dim= 0).shape

torch.Size([10, 20])

In [43]:
torch.mean(tensor1.float(), dim= 0).shape #need to convert to float as mean is not implemented for half

torch.Size([10, 20])

In [45]:
torch.eq(x, y) #for checking equality element wise

tensor([False, False, False])

In [51]:
z= torch.sort(tensor1, dim= 0, descending= False)
z.values.shape #sorts along dim 0

torch.Size([128, 10, 20])

In [55]:
z[0].shape, z[1].shape #it returns values and indices (that we swapped to get sorted values)

(torch.Size([128, 10, 20]), torch.Size([128, 10, 20]))

In [60]:
z= torch.clamp(tensor1, min= 0, max= 0.2) #clamps values between min and max that means if value is less than min then it will be min and if value is more than max then it will be max
#relu is speacial case of clamp

In [61]:
x= torch.tensor([1, 0, 1, 1, 1], dtype= torch.bool)
torch.any(x), torch.all(x)

(tensor(True), tensor(False))

In [62]:
#tensor indexing

In [66]:
batch_size= 10
features= 25
x= torch.rand((batch_size, features))

x[0].shape, x[:, 0].shape, x[2, 0:5].shape

(torch.Size([25]), torch.Size([10]), torch.Size([5]))

In [67]:
#can assign
x[0, 0]= 100

In [69]:
x= torch.arange(10)
indices= [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [70]:
x= torch.rand((3, 5))
rows= torch.tensor([1, 0])
cols= torch.tensor([4, 0]) #it will return 2 values, one from row 1 col 4 and other from row 0 col 0
x[rows, cols]

tensor([0.7525, 0.3840])

In [71]:
x= torch.arange(10)
print(x[(x<2) | (x>8)]) #it will return values that are less than 2 or greater than 8


tensor([0, 1, 9])


In [72]:
x[x.remainder(2) ==0]

tensor([0, 2, 4, 6, 8])

In [73]:
torch.where(x>5, x, x*2) #if x>5 then x else x*2

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [75]:
torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()

tensor([0, 1, 2, 3, 4])

In [77]:
x= torch.rand((3, 3))
x.ndimension()

2

In [78]:
x.numel() #number of elements

9

In [83]:
#tensor reshaping
x= torch.arange(9)
x_re= x.view(3, 3) #for view, memory blocks should be contiguous and this is different from reshape, for reshape it does not matter
#it simply copy if its not
x_re

x.reshape(3, 3)

#reshape is better as it can handle non contiguous memory blocks, but can have performance loss as view is faster and does not copy data, as copyinh data is expensive

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [87]:
y= x_re.t() #transpose
print(y)
y.contiguous().view(9) #if we want to reshape after transpose then we need to make it contiguous first
#be cautious of this as it can lead to memory errors

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [89]:
x= torch.rand(2, 5)
y= torch.rand(2, 5)

torch.cat((x, y), dim= 1).shape

torch.Size([2, 10])

In [90]:
x.view(-1).shape #it will flatten the tensor

torch.Size([10])

In [91]:
batch= 64
x= torch.rand((batch, 2, 5))
x.view((batch, -1)).shape

torch.Size([64, 10])

In [93]:
#for swtiching row with col
z= x.permute(0, 2, 1) #tranpose is speacial case of permute
z.shape, x.shape

(torch.Size([64, 5, 2]), torch.Size([64, 2, 5]))

In [94]:
x= torch.arange(10)
x.unsqueeze(0).shape, x.unsqueeze(1).shape

(torch.Size([1, 10]), torch.Size([10, 1]))

In [96]:
x= torch.arange(10).unsqueeze(0).unsqueeze(2)
x.shape

torch.Size([1, 10, 1])

In [98]:
x.squeeze(0).shape, x.squeeze(2).shape

(torch.Size([10, 1]), torch.Size([1, 10]))