In [2]:
# miners are components that help select informative pairs or triplets from a batch of data
# during the training process

# Miners are used to identify hard positives and hard negatives within a batch of data.

# Types of Miners
# PairMiner: Selects pairs of examples (anchor, positive) and (anchor, negative)

# based on certain criteria, such as the distance between them.

# TripletMiner: Selects triplets of examples (anchor, positive, negative) where the positive is of the same class as the anchor and the negative is of a different class. The miner ensures that the triplets selected are the most informative ones, often based on the margin criterion.

# MultiSimilarityMiner: Selects pairs based on multiple similarity metrics.


In [3]:
!pip install pytorch-metric-learning

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 kB 1.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [4]:
import torch
from pytorch_metric_learning import miners, losses

In [19]:
miner = miners.TripletMarginMiner(margin=0.2, type_of_triplets="hard")

#embeddings are the feature vectors produced by the model for the current batch of input data
embeddings = torch.randn(128, 512)
labels = torch.randint(0, 10, size=(128,))

# This line calls the miner with the embeddings and labels.
# The miner examines the distances between the embeddings and selects the
# hardest triplets according to the margin criterion.
# The output, hard_triplets, is a list or tensor of indices representing the selected triplets.
# These indices specify which samples in the batch are to be used as anchors, positives, and negatives.
a, p, n = miner(embeddings, labels)

In [20]:
a,p,n #the combinations are created

(tensor([  0,   0,   0,  ..., 127, 127, 127]),
 tensor([  4,   4,   4,  ..., 109, 109, 109]),
 tensor([  1,   2,   5,  ..., 121, 124, 125]))

In [21]:
loss_fn = losses.TripletMarginLoss(margin=0.2)

loss = loss_fn(embeddings, labels, (a, p, n))


In [22]:
loss

tensor(0.2344)